// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

/// Marks a sum type as canonically coded (`{"case": …}`, contracts/serialization.md §4)
/// with coders GENERATED by `tools/canonical-sum-gen` into
/// `<X>Serialization.generated.swift` — declare the conformance on the enum and run
/// the generator (CI drift-gates it via `--check`).
///
/// The `canonicalCodersGenerated` requirement exists to defeat SE-0295: without it,
/// a missing/stale generated file would let the compiler silently SYNTHESIZE
/// Codable in the wrong dialect. Only the generated file provides the member, so a
/// missing file fails compilation AT THE ENUM DECLARATION ("does not conform to
/// 'CanonicalSumCodable'") — the error points at the type, the fix is the generator.
public protocol CanonicalSumCodable: Codable {
  /// Provided ONLY by the generated coder file — never write this by hand.
  static var canonicalCodersGenerated: Bool { get }
}
